# Название рабочего процесса
name: test db connect 
 
# Определение событий, при которых запускается рабочий процесс
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

# Определение задач (jobs), которые будут выполняться
jobs:
  test:
    # Указывает, на какой виртуальной машине будет выполняться задача
    runs-on: ubuntu-latest

    # Определение сервисов, необходимых для работы задачи
    services:
      postgres:
        image: postgres:13
        env:
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: root
          POSTGRES_DB: exampleDB
        ports:
          - 5432:5432  
        options: >-
          --health-cmd "pg_isready -U postgres"
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
    # Последовательность шагов, выполняемых в рамках задачи
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3 

      - name: Set up Python 3.13
        uses: actions/setup-python@v4
        with:
          python-version: '3.13'

      - name: Install uv
        run: |
          curl -LsSf https://astral.sh/uv/install.sh | sh
          echo "$HOME/.uv/bin" >> $GITHUB_PATH
          uv --version
      - name: Synchronize dependencies with uv
        run: uv sync

      - name: Wait for PostgreSQL to be ready
        run: |
          until pg_isready -h localhost -p 5432; do
            echo "Waiting for PostgreSQL..."
            sleep 2
          done
      - name: Apply migrations
        working-directory: ./example
        run: uv run python manage.py migrate
      # запуск тестов с помощью встроенного unittest
      - name: Run unittests
        working-directory: ./example
        run: uv run python manage.py test
      # запуск тестов с помощью pytests
      - name: Run pytests
        working-directory: ./example
        run: uv run pytest -v