name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Python 3.11
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Install uv
        run: |
          # Устанавливаем uv через скрипт
          curl -LsSf https://astral.sh/uv/install.sh | sh
          # Добавляем uv в PATH
          echo "$HOME/.uv/bin" >> $GITHUB_PATH
          uv --version

      - name: Synchronize dependencies with uv
        run: uv sync

      - name: Apply migrations
        run: uv run python manage.py migrate

      - name: Run tests
        run: uv run python manage.py test
